
'''
Fig. 2C
Based on the  maximum common structure (MCS) similarity, we divided the annotated pairs into 5 class.
(High Similarity (>70%),Medium Similarity (45%-70%),Low Similarity (35%-45%), Not Similar (<35%), Not compared (under thresholds))

input:
    ./data/GNPS/**.csv (generated by Fig2_GNPS_Pre)

output:
    Data for visualizing in prism


'''
import time
import numpy as np
import pandas as pd
from rdkit import Chem
from rdkit.Chem import rdFMCS
from tqdm import trange
from my_packages.cheminfo_tools import MCS

if __name__ == '__main__':
    t = time.time()
    mps = 5
    thresholds = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
    # Loading filtered results
    for threshold in thresholds:
        fbmn_file = f'./data/GNPS/{threshold}_{mps}.csv'
        fbmn_df = pd.read_csv(fbmn_file)

        top1, H, M, L, NS, NC = 0, 0, 0, 0, 0, 0
        for i in range(len(fbmn_df)):
            mcs = fbmn_df.loc[i, 'mcs']
            if mcs == 1:
                top1 +=1 # Identical annotation
            elif mcs >= 0.7 and mcs < 1:
                H += 1 # High similar annotation
            elif mcs >= 0.45 and mcs < 0.7:
                M += 1 # Medium similar annotation
            elif mcs >= 0.35 and mcs < 0.45:
                L += 1 # Low similar annotation
            else:
                NS += 1 # Non-similar
        NC = 99 - H - M - L - NS - top1 # Unannotated features
        print(f'{NC}\t{NS}\t{L}\t{M}\t{H}\t{top1}') # Data for visualization (figure 2C)

    print(f'Finished in {(time.time() - t) / 60:.2f} min')
